core:
    resource: "@CoreBundle/Resources/config/routing.xml"
    prefix:   /

billet:
    resource: "@BilletBundle/Resources/config/routing.yml"
    prefix:   /louvre

app:
    resource: '@AppBundle/Controller/'
    type: annotation
