<?php

namespace BilletBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{

  public function getBillets()
   {
     $query = $this->createQueryBuilder('b')
       ->orderBy('b.date', 'DESC')
       ->getQuery()
     ;
     return $query->getResult();
   }

  public function getBilletWithCommande(array $commandeEmail)
  {
    $qb = $this->createQueryBuilder('b');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->innerJoin('b.commandes', 'c')
      ->addSelect('c')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('c.email', $commandeEmail));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult()
    ;
  }
}
