<?php

namespace BilletBundle\Repository;

/**
 * Choix_paysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Choix_paysRepository extends \Doctrine\ORM\EntityRepository
{
}
