<?php

namespace BilletBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCommandes()
   {
     $query = $this->createQueryBuilder('c')
       // Jointure sur l'attribut image
       ->leftJoin('c.billets', 'b')
       ->addSelect('b')
       ->orderBy('c.dateAchat', 'DESC')
       ->getQuery()
     ;
     return $query->getResult();
   }
}
