# Page d'accueil
Billet_home :
    path:    /
    defaults: {_controller: BilletBundle:Billet:add}
    methods: [POST,GET]

# Page de verification
Billet_verif :
    path:    /verif
    defaults: {_controller: BilletBundle:Billet:verif}
    methods: [POST,GET]

# Page de paiement
Billet_paiement :
    path:    /paiement
    defaults: {_controller: BilletBundle:Billet:paiement}
    methods: [POST,GET]

# Page de confirmation
Billet_confirmation :
    path:    /confirmation
    defaults: {_controller: BilletBundle:Billet:confirmation}
    methods: [POST,GET]

# Mentions légales
Billet_ticket_mentions:
    path:     /mentionlegal
    defaults: { _controller: LouvreShopBundle:Booking:mentionsLegal}
    methods: [GET]
