services:
#    billet.example:
#        class: BilletBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    billet.antispam:
        class: BilletBundle\Antispam\Antispam
        arguments:
            - "@mailer"
            - %locale%
            - 50
